spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/railway}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=false

server.port=${PORT:8080}
server.error.include-message=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
