spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=false

server.port=${PORT:8080}
server.error.include-message=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web=DEBUG

spring.main.allow-circular-references=true

#-- Admins --//
app.admin.emails=author@test.com

app.frontend.success-url=https://front-production-c924.up.railway.app/payment-success
app.frontend.cancel-url=https://front-production-c924.up.railway.app/payment-cancel

# CORS
app.cors.origins=https://front-production-c924.up.railway.app,http://localhost:5173

yookassa.shop-id=${YOOKASSA_SHOP_ID:test_shop_id}
yookassa.secret-key=${YOOKASSA_SECRET_KEY:test_secret_key}
yookassa.webhook-secret=${YOOKASSA_WEBHOOK_SECRET:test_wh_secret}

# ? CORS ???? ??? ??????
spring.web.cors.allowed-origins=https://front-production-c924.up.railway.app,http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false