spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=false

server.port=${PORT:8080}
server.error.include-message=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web=DEBUG

spring.main.allow-circular-references=true

//--- Admins ---//
app.admin.emails=author@test.com

# ??????? (???????? ?????)
# Stripe
stripe.webhook-secret=whsec_VjefcqqzGLOLu5LV7PB1p5i7KdbJ7rv5
stripe.secret-key=sk_test_51TCmfnDLUybEGqXcjFJpt5fxmpo0PROS6FAW0SWpv1OyyHthS8TmbFSwJUbFNRqzp7OMpTwZfPOoSQghSR4JwVGv00IVeoaHlF


# ???? ??????? ???????????? ????? ?????? / ??????
app.frontend.success-url=https://front-production-c924.up.railway.app/payment-success
app.frontend.cancel-url=https://front-production-c924.up.railway.app/payment-cancel

# CORS (????? ??????)
app.cors.origins=https://front-production-c924.up.railway.app,http://localhost:5173